#version: '3.7'
#
#services:
#  postgresql:
#    image: postgres:12-alpine
#    restart: unless-stopped
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_DB: loginpage
#      POSTGRES_USER: loginpage
#      POSTGRES_PASSWORD: loginpage
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#volumes:
#  postgres-data:
#    driver: local